// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SerialDisplay

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_scnMain;
lv_obj_t * ui_pnlHeader;
lv_obj_t * ui_lblHeader;
lv_obj_t * ui_txtSerial;
void ui_event_txtInput(lv_event_t * e);
lv_obj_t * ui_txtInput;
lv_obj_t * ui_btnSend;
lv_obj_t * ui_lblSendBtn;
lv_obj_t * ui_keyboardInput;
lv_obj_t * ui_scnPlotter;
lv_obj_t * ui_pnlPlotterHdr;
lv_obj_t * ui_lblPlotterHdr;
lv_obj_t * ui_chtPlotter;
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_txtInput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_keyboardInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_keyboardInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        
    }
}

///////////////////// SCREENS ////////////////////
void ui_scnMain_screen_init(void)
{
    ui_scnMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scnMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_scnMain, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_scnMain, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_pnlHeader = lv_obj_create(ui_scnMain);
    lv_obj_set_height(ui_pnlHeader, 50);
    lv_obj_set_width(ui_pnlHeader, lv_pct(100));
    lv_obj_set_align(ui_pnlHeader, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHeader = lv_label_create(ui_pnlHeader);
    lv_obj_set_width(ui_lblHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHeader, "Serial Monitor");
    lv_obj_set_style_text_color(ui_lblHeader, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblHeader, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtSerial = lv_textarea_create(ui_scnMain);
    lv_obj_set_width(ui_txtSerial, lv_pct(99));
    lv_obj_set_height(ui_txtSerial, lv_pct(79));
    lv_obj_set_x(ui_txtSerial, -17);
    lv_obj_set_y(ui_txtSerial, 60);
    lv_obj_set_align(ui_txtSerial, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtSerial, "Waiting for serial...");
    lv_obj_set_style_text_color(ui_txtSerial, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtSerial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtSerial, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtInput = lv_textarea_create(ui_scnMain);
    lv_obj_set_height(ui_txtInput, 57);
    lv_obj_set_width(ui_txtInput, lv_pct(75));
    lv_obj_set_align(ui_txtInput, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtInput, "Placeholder...");
    lv_obj_add_flag(ui_txtInput, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_btnSend = lv_btn_create(ui_scnMain);
    lv_obj_set_width(ui_btnSend, 62);
    lv_obj_set_height(ui_btnSend, 50);
    lv_obj_set_align(ui_btnSend, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSend, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSend, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSend, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSend, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSendBtn = lv_label_create(ui_btnSend);
    lv_obj_set_width(ui_lblSendBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSendBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSendBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSendBtn, ">>");
    lv_obj_set_style_text_color(ui_lblSendBtn, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSendBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_keyboardInput = lv_keyboard_create(ui_scnMain);
    lv_obj_set_width(ui_keyboardInput, 300);
    lv_obj_set_height(ui_keyboardInput, 120);
    lv_obj_set_x(ui_keyboardInput, 0);
    lv_obj_set_y(ui_keyboardInput, 105);
    lv_obj_set_align(ui_keyboardInput, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_keyboardInput, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING);     /// Flags

    lv_obj_add_event_cb(ui_txtInput, ui_event_txtInput, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_keyboardInput, ui_txtInput);

}
void ui_scnPlotter_screen_init(void)
{
    ui_scnPlotter = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scnPlotter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_scnPlotter, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_scnPlotter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

    ui_pnlPlotterHdr = lv_obj_create(ui_scnPlotter);
    lv_obj_set_height(ui_pnlPlotterHdr, 50);
    lv_obj_set_width(ui_pnlPlotterHdr, lv_pct(100));
    lv_obj_set_align(ui_pnlPlotterHdr, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlPlotterHdr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlPlotterHdr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlPlotterHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPlotterHdr = lv_label_create(ui_pnlPlotterHdr);
    lv_obj_set_width(ui_lblPlotterHdr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPlotterHdr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblPlotterHdr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPlotterHdr, "Serial Plotter");
    lv_obj_set_style_text_color(ui_lblPlotterHdr, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPlotterHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPlotterHdr, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chtPlotter = lv_chart_create(ui_scnPlotter);
    lv_obj_set_width(ui_chtPlotter, lv_pct(80));
    lv_obj_set_height(ui_chtPlotter, lv_pct(60));
    lv_obj_set_x(ui_chtPlotter, -5);
    lv_obj_set_y(ui_chtPlotter, 91);
    lv_obj_set_align(ui_chtPlotter, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_chtPlotter, LV_CHART_TYPE_LINE);
    lv_chart_set_div_line_count(ui_chtPlotter, 10, 20);
    lv_chart_set_axis_tick(ui_chtPlotter, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_chtPlotter, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_series_t * ui_chtPlotter_series_1 = lv_chart_add_series(ui_chtPlotter, lv_color_hex(0x120091),
                                                                     LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_chtPlotter_series_1_array[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    lv_chart_set_ext_y_array(ui_chtPlotter, ui_chtPlotter_series_1, ui_chtPlotter_series_1_array);
    lv_chart_series_t * ui_chtPlotter_series_2 = lv_chart_add_series(ui_chtPlotter, lv_color_hex(0xFF0000),
                                                                     LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_chtPlotter_series_2_array[] = { 10, 20, 40, 80, 80, 40, 20, 10, 0, 100 };
    lv_chart_set_ext_y_array(ui_chtPlotter, ui_chtPlotter_series_2, ui_chtPlotter_series_2_array);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scnMain_screen_init();
    ui_scnPlotter_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_scnMain);
}
