// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SerialDisplay

#ifndef _SERIALDISPLAY_UI_H
#define _SERIALDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t * ui_scnMain;
extern lv_obj_t * ui_pnlHeader;
extern lv_obj_t * ui_lblHeader;
extern lv_obj_t * ui_txtSerial;
void ui_event_txtInput(lv_event_t * e);
extern lv_obj_t * ui_txtInput;
extern lv_obj_t * ui_btnSend;
extern lv_obj_t * ui_lblSendBtn;
extern lv_obj_t * ui_keyboardInput;
extern lv_obj_t * ui_scnPlotter;
extern lv_obj_t * ui_pnlPlotterHdr;
extern lv_obj_t * ui_lblPlotterHdr;
extern lv_obj_t * ui_chtPlotter;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
